### ISSUE TITLE
Test of details block

### ISSUE THREAD

**Issue by jmeridth** [jmeridth/jmeridth.github.io#3]
Thank you @rheinwein for showing me how to use `<details>...</details>` with your comment [here](https://github.com/docker/docker/issues/20316#issuecomment-232901660). I did not know this was available. 

<details>
<summary>

a possible stacktrace</summary>

I could be a stacktrace and make it easier to read
</details>

<details>
<summary>

Hi</summary>

I'm hidden too
<details>

**Comment by bfosberry** [comment]
_gasp_
